sudo: false
language: ruby
cache: bundler

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk
      - wget
      - unzip
      - ssh

matrix:
  include:
    # WE SUPPORT UPGRADES OF CHEF 11.x on RUBY 1.9.3 VIA chef_client_updater COOKBOOK
  - rvm: 1.9.3
    bundler_args: --without chefstyle functional --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
    script:
      - bundle exec rake unit
      - bundle exec rake functional
    - rvm: 2.0
    - rvm: 2.1.10
    - rvm: 2.2.10
    - rvm: 2.3.7
    - rvm: 2.4.4
    - rvm: 2.5.1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

branches:
  only:
  - master

script:
  - bundle exec rake travis:ci
  # - ci/run-acceptance-tests.sh
