language: ruby
sudo: false
dist: precise
cache: bundler

addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk
      - wget
      - unzip
      - ssh

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

branches:
  only:
  - master

matrix:
  include:
    # WE SUPPORT UPGRADES OF CHEF 11.x on RUBY 1.9.3 VIA chef_client_updater COOKBOOK
  - rvm: 1.9.3
    bundler_args: --without chefstyle functional --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
    script:
      - bundle exec rake unit
      - bundle exec rake functional
  - rvm: 2.0
  - rvm: 2.2
  - rvm: 2.3
  - rvm: 2.4
  - rvm: 2.5.1
  # - rvm: 2.3
  #   env: SUITE=ubuntu
  # - rvm: 2.3
  #   env: SUITE=windows-server
  # - rvm: 2.3
  #   env: SUITE=centos

# before_script:
#   - ci/before-script.sh
#   # put terraform on PATH
#   - export PATH="$PWD/bin:$PATH"

script:
  - bundle exec rake travis:ci
  # - ci/run-acceptance-tests.sh
