language: ruby
sudo: false
rvm:
  - 2.2
  - 2.1

before_script:
  - export APPBUNDLER_ALLOW_RVM=true
script: 
  - bundle install
  - bundle exec rake
  - cd acceptance/ && bundle install && bundle exec chef-acceptance version
