driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  product_name: chef
  product_version: latest
  channel: current

platforms:
  - name: centos-6.5
    run_list:
  - name: debian-7.4
    run_list:
  - name: freebsd-10.0
    run_list:
  - name: ubuntu-14.04
    run_list:
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private
  # - name: windows-7-professional
  #   provisioner:
  #     name: windows_chef_zero
  #     require_chef_omnibus: 11.12.4
  #   driver:
  #     box: chef/windows-7-professional # private

suites:
  - name: mixlib-install-chef
    run_list:
  - name: mixlib-install-chefdk
    provisioner:
      product_name: chefdk
      product_version: latest
      channel: current
