driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    run_list:
  - name: debian-7.4
    run_list:
  - name: freebsd-10.0
    run_list:
  - name: ubuntu-14.04
    run_list:
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private
  - name: windows-server-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard # private

suites:
  - name: chef-unstable-install
    provisioner:
      product_name: chef
      product_version: 12.5.1+20151210002019
      channel: unstable
    run_list:
  - name: chefdk-unstable-install
    excludes: [ 'freebsd-10.0' ]
    provisioner:
      product_name: chefdk
      product_version: 0.10.0+20151209030614
      channel: unstable
    run_list:
